version: "3"
services:
  gateway:
    image: envoyproxy/envoy:v1.28.0
    command: ["-c", "/etc/envoy/envoy.yaml", "--log-level", "warn"]
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
  authz:
    build:
      context: .
    ports:
      - "3000:3000"
      - "9229:9229"
  api:
    build:
      context: .
    ports:
      - "3001:3000"
